diff -Naur a/lang/python/hu/LC_MESSAGES/python.po b/lang/python/hu/LC_MESSAGES/python.po
--- a/lang/python/hu/LC_MESSAGES/python.po	2022-03-21 15:19:44.000000000 +0100
+++ b/lang/python/hu/LC_MESSAGES/python.po	2022-03-21 20:21:11.142495851 +0100
@@ -26,7 +26,7 @@
 
 #: src/modules/initramfscfg/main.py:32
 msgid "Configuring initramfs."
-msgstr "initramfs konfigurálása."
+msgstr "Az initramfs konfigurálása."
 
 #: src/modules/initramfscfg/main.py:85 src/modules/initramfscfg/main.py:89
 #: src/modules/fstab/main.py:360 src/modules/fstab/main.py:366
@@ -82,11 +82,11 @@
 
 #: src/modules/dracut/main.py:27
 msgid "Creating initramfs with dracut."
-msgstr "initramfs létrehozása ezzel: dracut."
+msgstr "initramfs létrehozása a dracut programmal."
 
 #: src/modules/dracut/main.py:49
 msgid "Failed to run dracut on the target"
-msgstr "dracut futtatása nem sikerült a célon."
+msgstr "A dracut futtatása nem sikerült."
 
 #: src/modules/dracut/main.py:50 src/modules/mkinitfs/main.py:50
 msgid "The exit code was {}"
@@ -134,17 +134,18 @@
 
 #: src/modules/displaymanager/main.py:991
 msgid "No display managers selected for the displaymanager module."
-msgstr "Nincs kijelzőkezelő kiválasztva a kijelzőkezelő modulhoz."
+msgstr "Nincs kiválasztott grafikus beléptetö a megfelelő modulhoz."
 
 #: src/modules/displaymanager/main.py:992
 msgid ""
 "The displaymanagers list is empty or undefined in both globalstorage and "
 "displaymanager.conf."
-msgstr ""
+msgstr "A beléptetők listája üres, vagy nincs megadva a sem globalstorage-ben sem"
+" a displaymanager.conf fájlban."
 
 #: src/modules/displaymanager/main.py:1074
 msgid "Display manager configuration was incomplete"
-msgstr "A kijelzőkezelő konfigurációja hiányos volt"
+msgstr "A grafikus beléptető konfigurációja hiányos volt"
 
 #: src/modules/services-openrc/main.py:29
 msgid "Configure OpenRC services"
@@ -169,7 +170,7 @@
 #: src/modules/services-openrc/main.py:93
 #: src/modules/services-systemd/main.py:59
 msgid "Cannot modify service"
-msgstr "a szolgáltatást nem lehet módosítani"
+msgstr "A szolgáltatást nem lehet módosítani"
 
 #: src/modules/services-openrc/main.py:94
 msgid ""
@@ -261,7 +262,7 @@
 
 #: src/modules/localecfg/main.py:30
 msgid "Configuring locales."
-msgstr "nyelvi értékek konfigurálása."
+msgstr "Nyelvi beállítások."
 
 #: src/modules/mount/main.py:42
 msgid "Mounting partitions."
@@ -298,7 +299,7 @@
 #: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:93
 #: src/modules/dummypython/main.py:94
 msgid "Dummy python step {}"
-msgstr "Hamis {}. Python lépés"
+msgstr "Hamis Python lépés: {}"
 
 #: src/modules/hwclock/main.py:26
 msgid "Setting hardware clock."
@@ -358,11 +359,11 @@
 
 #: src/modules/unpackfs/main.py:34
 msgid "Filling up filesystems."
-msgstr "Fájlrendszerek betöltése."
+msgstr "Fájlrendszerek átmásolása."
 
 #: src/modules/unpackfs/main.py:254
 msgid "rsync failed with error code {}."
-msgstr "az rsync elhalt a(z) {} hibakóddal"
+msgstr "Az rsync elhalt a(z) {} hibakóddal"
 
 #: src/modules/unpackfs/main.py:299
 msgid "Unpacking image {}/{}, file {}/{}"
@@ -378,7 +379,7 @@
 
 #: src/modules/unpackfs/main.py:430
 msgid "No mount point for root partition"
-msgstr "Nincs betöltési pont a root partíciónál"
+msgstr "Nincs csatolási pont a root partíciónál"
 
 #: src/modules/unpackfs/main.py:431
 msgid "globalstorage does not contain a \"rootMountPoint\" key."
@@ -386,7 +387,7 @@
 
 #: src/modules/unpackfs/main.py:434
 msgid "Bad mount point for root partition"
-msgstr "Rossz betöltési pont a root partíciónál"
+msgstr "Rossz csatolási pont a root partíciónál"
 
 #: src/modules/unpackfs/main.py:435
 msgid "rootMountPoint is \"{}\", which does not exist."
@@ -415,6 +416,7 @@
 "Failed to find unsquashfs, make sure you have the squashfs-tools package "
 "installed."
 msgstr ""
+"Az unsquashfs nem található, a squashfs-tools csomag telepítve van?"
 
 #: src/modules/unpackfs/main.py:481
 msgid "The destination \"{}\" in the target system is not a directory"
